apiVersion: v1
kind: ConfigMap
metadata:
  name: expense-tracker-config
  namespace: expense-tracker
data:
  NODE_ENV: "production"
  PORT: "5000"
  JWT_EXPIRE: "7d"
  CORS_ORIGIN: "https://expense.premiertickets.biz"
  VITE_API_URL: "https://expense.premiertickets.biz/api"
