apiVersion: v1
kind: Secret
metadata:
  name: expense-tracker-secrets
  namespace: expense-tracker
type: Opaque
stringData:
  jwt-secret: "531e63b4c9e2d3403ab05bd6b4a73a5b0bed1923ef3232f0e83eba71c78bf6df440e52d48c9e07422385046da6000650fc04c1ac87c9a4aa0af3161a8bc93834"
  mongodb-uri: "mongodb://mongodb-service:27017/expense-tracker"
