apiVersion: v1
kind: Secret
metadata:
  name: expense-tracker-secrets
  namespace: expense-tracker
type: Opaque
stringData:
  jwt-secret: "CHANGE_THIS_TO_A_SECURE_RANDOM_STRING_AT_LEAST_32_CHARS"
  mongodb-uri: "mongodb://mongodb-service:27017/expense-tracker"
